# Generated by Django 6.0.5 on 2026-05-20 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('count', models.BigIntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='counts.host')),
            ],
            options={
                'indexes': [models.Index(fields=['host', 'date'], name='counts_coun_host_id_efbcd1_idx'), models.Index(fields=['host', 'metric'], name='counts_coun_host_id_81de43_idx')],
                'unique_together': {('host', 'date', 'metric', 'value')},
            },
        ),
    ]
