# Generated by Django 6.0.5 on 2026-09-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.host'),
        ),
    ]
