# Generated by Django 6.0.5 on 2026-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_user_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.IntegerField(default=0, help_text='UTC offset in hours'),
        ),
    ]
