# Generated by Django 6.0.5 on 2026-09-05 21:20

from django.db import migrations, models

RANGES = ["day", "yesterday", "last7", "last30", "month", "year", "all"]


def backfill_prefs(apps, schema_editor):
    """Promote prefs["site"]/prefs["range"] into the new columns and drop
    them from the blob (the rest of prefs stays untouched)."""
    User = apps.get_model("counter", "User")
    for user in User.objects.iterator():
        prefs = dict(user.prefs or {})
        user.selected_site = prefs.pop("site", "") or ""
        range_value = prefs.pop("range", None)
        user.date_range = range_value if range_value in RANGES else "day"
        user.prefs = prefs
        user.save(update_fields=["selected_site", "date_range", "prefs"])


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_alter_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_range',
            field=models.CharField(choices=[('day', 'day'), ('yesterday', 'yesterday'), ('last7', 'last7'), ('last30', 'last30'), ('month', 'month'), ('year', 'year'), ('all', 'all')], default='day', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_site',
            field=models.CharField(blank=True, default='', max_length=253),
        ),
        migrations.RunPython(backfill_prefs, migrations.RunPython.noop),
    ]