services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "6379:6379"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "5432:5432"
