include:
  - services/frontend/compose.yaml
  - services/backend/compose.yaml
  - services/tracker/compose.yaml
  - services/redis/compose.yaml
  - services/postgres/compose.yaml

volumes:
  redis_data:
  postgres_data:
