# Generated by Django 5.2.14 on 2026-05-14 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('filter_allowed_domains', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('count', models.BigIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='analytics.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'date'], name='analytics_c_site_id_cc1f44_idx'), models.Index(fields=['site', 'metric'], name='analytics_c_site_id_d16070_idx')],
                'unique_together': {('site', 'date', 'metric', 'value')},
            },
        ),
    ]
