#!/usr/bin/env uv run --script
# /// script
# dependencies = [
#     "llm",
#     "llm-anthropic",
#     "claudia-agent",
#     "pyyaml",
# ]
# ///


from pathlib import Path

from llm_tools_mcp.register_tools import MCP
from claudia.backends.agent import run as claudia_run
from claudia.backends.agent import CoderToolbox
from claudia.backends.agent import die
from claudia.utils import get_project_files, get_project_map



SYSTEM_PROMPT = """
You are a planning agent.

# Task
Break up the given ticket into just a few still high-level, short subtickets. A subticket consits of just a few short bullet points.

# Project map
{project_map}

""".strip()


def add_ticket(title:str, content:str) -> None:
    print(f"======== {title}")
    print(content)
    print()
    print()

def get_tools(*, workdir, devbox, ui, model):


    coder = CoderToolbox(ui=ui, workdir=workdir, model=model)


    return [
        # svelte_mcp_tool,
        # coder,
        coder.read_files,
        add_ticket,
    ]


# import llm
# model = llm.get_model("anthropic/claude-opus-4-8")


claudia_run(get_tools=get_tools, system_prompt=SYSTEM_PROMPT) #, model=model)
