# Generated by Django 6.0.5 on 2026-05-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='count',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.host'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='count',
            index=models.Index(fields=['host', 'date'], name='core_count_host_id_ef779d_idx'),
        ),
        migrations.AddIndex(
            model_name='count',
            index=models.Index(fields=['host', 'category'], name='core_count_host_id_295392_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='count',
            unique_together={('host', 'date', 'category', 'item')},
        ),
    ]
