# Generated by Django 6.0.5 on 2026-05-27 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='count',
            name='core_coun_host_id_81de43_idx',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='metric',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='value',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='count',
            new_name='total',
        ),
        migrations.RenameIndex(
            model_name='count',
            new_name='core_count_host_id_ef779d_idx',
            old_name='core_coun_host_id_efbcd1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='count',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='count',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.host'),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='count',
            unique_together={('host', 'date', 'category', 'item')},
        ),
        migrations.AddIndex(
            model_name='count',
            index=models.Index(fields=['host', 'category'], name='core_count_host_id_295392_idx'),
        ),
    ]
