# Generated by Django 6.0.5 on 2026-05-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_avatar_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='filter_allowed_domains',
            new_name='hide_hosts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allowed_domains',
        ),
    ]
