# Generated by Django 6.0.5 on 2026-05-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_filter_allowed_domains_userprofile_hide_hosts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
